DROP TABLE IF EXISTS RR;
DROP TABLE IF EXISTS Cache;

CREATE TABLE "RR" (
	"Name"	TEXT NOT NULL,
	"TTL"	INTEGER NOT NULL,
	"Class"	INTEGER NOT NULL,
	"Type"	INTEGER NOT NULL,
	"RDATA"	TEXT NOT NULL,
	"RDLENGTH"	INTEGER,
	PRIMARY KEY("Name","Type")
);
CREATE TABLE "Cache" (
	"Name"	TEXT NOT NULL,
	"TTL"	INTEGER NOT NULL,
	"Class"	INTEGER NOT NULL,
	"Type"	INTEGER NOT NULL,
	"RDATA"	TEXT NOT NULL,
	"RDLENGTH"	INTEGER,
	"DateAdded"	INTEGER,
	PRIMARY KEY("Name","Type")
);